// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpugiyzopdiqtkvxuxpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwdWdpeXpvcGRpcXRrdnh1eHBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MjIzOTYsImV4cCI6MjA3MTA5ODM5Nn0.OZN0t0WB-hBEDxxnSDpAmlC_y43wFDfaTkRvj9uk94A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});